name: CI build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install pip
      run: |
        python -m pip install --upgrade pip

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Download model files
      run: |
        mkdir -p onnx
        gh release download v0.0.1-alpha -p "onnx.zip"
        unzip onnx.zip -d .
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Make run_tests.sh executable
      run: chmod +x run_tests.sh

    - name: Run tests
      run: ./run_tests.sh
